- name: Install Nginx
  hosts: all
<<<<<<< HEAD
  #become: yes
  tasks:
=======
    tasks:
>>>>>>> 003180b (Removed sudo for AWX container)
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
